// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/coming-soon": {
    params: {};
  };
  "/rozkroj-plyt-meblowych": {
    params: {};
  };
  "/rozkroj-plyt-meblowych/druk": {
    params: {};
  };
  "/blog": {
    params: {};
  };
  "/blog/:slug": {
    params: {
      "slug": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/coming-soon" | "/rozkroj-plyt-meblowych" | "/rozkroj-plyt-meblowych/druk" | "/blog" | "/blog/:slug";
  };
  "routes/index.tsx": {
    id: "routes/index";
    page: "/";
  };
  "routes/coming-soon.tsx": {
    id: "routes/coming-soon";
    page: "/coming-soon";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/rozkroj-plyt-meblowych";
  };
  "routes/print-layout.tsx": {
    id: "routes/print-layout";
    page: "/rozkroj-plyt-meblowych/druk";
  };
  "routes/blog.tsx": {
    id: "routes/blog";
    page: "/blog";
  };
  "routes/blog-post.tsx": {
    id: "routes/blog-post";
    page: "/blog/:slug";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/index": typeof import("./app/routes/index.tsx");
  "routes/coming-soon": typeof import("./app/routes/coming-soon.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/print-layout": typeof import("./app/routes/print-layout.tsx");
  "routes/blog": typeof import("./app/routes/blog.tsx");
  "routes/blog-post": typeof import("./app/routes/blog-post.tsx");
};